/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/pagoda.glb 
Author: kaungkaung159 (https://sketchfab.com/kaungkaung159)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shwedagon-pagoda-by-kyaw-lin-htet-ffca3e0400144a48aad10cd314364fd5
Title: ShweDagon Pagoda by Kyaw Lin Htet
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  // Served from /public; with VITE_BASE this resolves correctly. The 2nd arg
  // (true) enables the Draco decoder for the compressed .glb.
  const { nodes, materials } = useGLTF(import.meta.env.BASE_URL + 'pagoda-draco.glb', true)
  return (
    <group {...props} dispose={null}>
      <group position={[0.079, -1.605, 0]} scale={[1.001, 1.001, 1.083]}>
        <mesh geometry={nodes.Object_6.geometry} material={materials.Scratched_Gold} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Scratched_Gold} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Scratched_Gold} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Scratched_Gold} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Scratched_Gold} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Scratched_Gold} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Scratched_Gold} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Scratched_Gold} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Scratched_Gold} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Scratched_Gold} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Scratched_Gold} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.Scratched_Gold} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Scratched_Gold} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.Scratched_Gold} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Scratched_Gold} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.Scratched_Gold} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.Scratched_Gold} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.Scratched_Gold} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.Scratched_Gold} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.Scratched_Gold} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.Scratched_Gold} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.Scratched_Gold} />
        <mesh geometry={nodes.Object_28.geometry} material={materials['Scratched_Gold.001']} />
        <mesh geometry={nodes.Object_29.geometry} material={materials['Scratched_Gold.003']} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.material_0} position={[1.416, 6.166, 2.404]} rotation={[1.449, -0.715, -1.748]} scale={0.564} />
    </group>
  )
}

useGLTF.preload(import.meta.env.BASE_URL + 'pagoda-draco.glb', true)
